### ISSUE TITLE
`card-item` lardagi `3` va `6` - `card` laringizdagi `img` lar tepaga chiqib qolgan

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [darxanov/n24#9]
buni to'g'riash uchun  `card-item` ga `display: flex;`   `flex-direction: column;`  berasiz hamda `img` ga `margin-top: auto;             
 ` berasiz `#fix` bo'ladi, sizda bunday bo'lmadi sababi:  `a` ni ichiga `h2` joylagansiz...    aslida   `h3` bo'ladi va  uning ichida  `a` bo'ladi

**Comment by darxanov** [comment]
Menda ishlamadi
